#!/usr/bin/env node
// Copies LICENSE.md and THIRD_PARTY_NOTICES.md into assets/web/legal.js so the app can show them (Settings ->
// Licenses & credits). Run it after editing either file: node tools/gen-legal.js. tests/legal.test.js fails if it's stale.
'use strict';
const fs = require('fs'), path = require('path');
const root = path.join(__dirname, '..');
function build() {
  const read = (f) => fs.readFileSync(path.join(root, f), 'utf8');
  return '/* Generated by tools/gen-legal.js from LICENSE.md and THIRD_PARTY_NOTICES.md. Do not edit by hand. */\n' +
    'window.LEGAL = ' + JSON.stringify({ license: read('LICENSE.md'), notices: read('THIRD_PARTY_NOTICES.md') }, null, 1) + ';\n';
}
module.exports = { build, out: path.join(root, 'assets', 'web', 'legal.js') };
if (require.main === module) { fs.writeFileSync(module.exports.out, build()); console.log('wrote', path.relative(root, module.exports.out)); }
